- name: test
  hosts: localhost

  tasks:
  - name: create dir for work
    file:
      path: /data
      state: directory

  - name: copy chart to host
    copy:
      src: ../helm/db
      dest: /data/db

#  - name: add helm repo
#    shell: helm repo add my-repo https://charts.bitnami.com/bitnami

#check if postgres alredy exists

  - name: upgrade chart 
    shell: ' microk8s helm install test /data/db'
    #add when for first launch